version: '3.8'

services:
  app:
    build: .
    container_name: authenticute_app
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    command: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        python -c 'from app.database import create_tables; create_tables()' &&
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      " 